# VM3 — saul — 172.31.253.25 — Storage & Viz
# MinIO : zunesha — 172.31.250.57 — 175GB 
version: '3.8'

services:

  postgres:
    image: postgres:15
    container_name: uconnect-postgres
    ports:
      - "0.0.0.0:5432:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./infra/postgres/init:/docker-entrypoint-initdb.d
    networks:
      - uconnect-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 5s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server:24.3
    container_name: uconnect-clickhouse
    ports:
      - "0.0.0.0:8123:8123"
      - "0.0.0.0:9000:9000"
    environment:
      CLICKHOUSE_DB: ${CLICKHOUSE_DB}
      CLICKHOUSE_USER: ${CLICKHOUSE_USER}
      CLICKHOUSE_PASSWORD: ${CLICKHOUSE_PASSWORD}
    volumes:
      - clickhouse-data:/var/lib/clickhouse
    networks:
      - uconnect-net
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "clickhouse-client --user=${CLICKHOUSE_USER} --password=${CLICKHOUSE_PASSWORD} --query='SELECT 1'"]
      interval: 10s
      timeout: 5s
      retries: 5

  streamlit:
    build: ./streamlit
    container_name: uconnect-streamlit
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "0.0.0.0:8501:8501"
    environment:
      PG_HOST: postgres
      PG_PORT: 5432
      PG_DB: ${POSTGRES_DB}
      PG_USER: ${POSTGRES_USER}
      PG_PASSWORD: ${POSTGRES_PASSWORD}
      PG_SCHEMA: datamart
    networks:
      - uconnect-net
    restart: unless-stopped

  superset:
    image: apache/superset:latest-dev
    container_name: uconnect-superset
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8088:8088"
    environment:
      SUPERSET_SECRET_KEY: ${SUPERSET_SECRET_KEY}
      DATABASE_URL: postgresql+psycopg2://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/superset_db
    volumes:
      - superset-data:/app/superset_home
      - ./infra/superset/superset_config.py:/app/pythonpath/superset_config.py
    networks:
      - uconnect-net
    restart: unless-stopped

networks:
  uconnect-net:
    driver: bridge

volumes:
  postgres-data:
  superset-data:
  clickhouse-data:
